-- Единая Postgres-схема Невариум CRM — эквивалент всех 11 миграций SQLite
-- (server/db.js, MIGRATIONS), собранных в её нынешнем виде, а не перенесённых
-- по шагам: в CRM на момент перевода ноль пользователей и ноль заявок, переносить
-- нечего (docs/CRM_POSTGRES_MIGRATION_SPEC.md в nevarium-lab#3).
--
-- Все объекты — IF NOT EXISTS: применяется на каждом старте сервера (см.
-- server/db.js:openDb), безопасно при повторном запуске на уже готовой базе.
--
-- Даты и время — TEXT (ISO-8601, как отдаёт JS `now()`/`toISOString()`), не
-- TIMESTAMPTZ: весь существующий код сравнивает эти поля как строки
-- (`WHERE created_at >= ?`, `ORDER BY due_date`, `due_date < ?` с mskToday()) —
-- строки ISO-8601 сравниваются лексикографически идентично временнóму порядку,
-- так что это сохраняет 100% совместимость с бизнес-логикой без единой правки
-- сравнений дат по всему app.js (минимальное отклонение — прямое требование ТЗ).
--
-- Булевы поля (archived/done/demo/suspicious/text_truncated) — INTEGER 0/1, не
-- BOOLEAN: та же причина, не трогать сравнения вида `archived = 0` по всему коду
-- (осознанно исключено из этой работы, см. ТЗ).
--
-- project_id/winback_sequence_id теперь С НАСТОЯЩИМ FOREIGN KEY (в SQLite не было
-- REFERENCES — то была обходка ограничения SQLite на ALTER TABLE ADD COLUMN с
-- REFERENCES и ненулевым дефолтом, не намеренное архитектурное решение; Postgres
-- такого ограничения не имеет, и оба поля безопасны для FK: projects/
-- winback_sequences не входят в JSON-дамп и не участвуют в его перезаписи при
-- импорте — см. DUMP_TABLES в этом же файле, EXTRA_COLS/PLAIN_COLS в app.js).
--
-- ВАЖНО для кода, который вставляет строки с ЯВНЫМ id в таблицы ниже (проектный
-- сид в openDb(), POST /api/crm/import): явная вставка id НЕ продвигает identity-
-- последовательность автоматически — ни в pg-mem, ни в настоящем Postgres (это
-- реальное поведение GENERATED BY DEFAULT AS IDENTITY, не баг эмулятора,
-- пойманное смоук-тестом адаптера). Без явного `SELECT setval(pg_get_serial_
-- sequence('<table>','id'), (SELECT MAX(id) FROM <table>))` после такой вставки
-- следующий органический INSERT рано или поздно получит auto-id, который уже
-- занят восстановленной строкой, и упадёт на PRIMARY KEY constraint. Каждое
-- место, вставляющее явный id, обязано вызвать setval для своей таблицы сразу
-- после — планируется в server/db.js (сид projects) и в обработчике импорта
-- (server/app.js) при их переводе.
--
-- GENERATED BY DEFAULT AS IDENTITY (не ALWAYS) — на id ВОСЬМИ таблиц ниже
-- (projects, contacts, deals, tasks, interactions, pd_requests, audit_log,
-- consents), а не везде: POST /api/crm/import вставляет строки с ИХ ИСХОДНЫМИ
-- id, чтобы не порвать связи между восстановленными записями (app.js,
-- `INSERT INTO ${n} (id, ...) VALUES (@id, ...)` — все таблицы из DUMP_TABLES в
-- server/db.js), а сид данных projects прописывает id 1/2 явно (DEFAULT_PROJECT_ID
-- и весь код, где project_id захардкожен). GENERATED ALWAYS (обычная строгая
-- identity-колонка) этого не позволяет — «cannot insert into column "id"» — и
-- это НЕ баг, а корректное поведение Postgres, в отличие от более снисходительного
-- SQLite AUTOINCREMENT, который явную вставку id всегда разрешал. Найдено
-- смоук-тестом адаптера (tmp-smoke-adapter.mjs) ДО того, как это стало ошибкой
-- за сотней мест кода — users/outbox/winback_sequences/idempotency_keys явного
-- INSERT по id нигде не получают, там осталось GENERATED ALWAYS.
--
-- pd_requests.contact_id и consents.contact_id/deal_id — БЕЗ FOREIGN KEY,
-- намеренно, как и в SQLite: это юридическое доказательство (152-ФЗ), которое
-- обязано пережить восстановление из дампа, предшествующего появлению этих полей
-- (контакты/сделки тогда стираются и вставляются заново с НОВЫМИ id) — см.
-- CLAUDE.md, разделы про pd_requests.requester и consents.requester, и раунды
-- 17/21/23/25 ADR-015 (docs/DECISIONS.md) про недопустимость строгой ссылки здесь.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  token_version INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  archived INTEGER NOT NULL DEFAULT 0,
  origins TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  messenger TEXT DEFAULT '',
  note TEXT DEFAULT '',
  source TEXT NOT NULL DEFAULT 'manual',
  suspicious INTEGER NOT NULL DEFAULT 0,
  archived INTEGER NOT NULL DEFAULT 0,
  demo INTEGER NOT NULL DEFAULT 0,
  project_id INTEGER NOT NULL DEFAULT 1 REFERENCES projects(id),
  anonymized_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER NOT NULL REFERENCES contacts(id),
  title TEXT NOT NULL,
  stage TEXT NOT NULL DEFAULT 'Новый',
  amount INTEGER,
  note TEXT DEFAULT '',
  closed_at TEXT,
  demo INTEGER NOT NULL DEFAULT 0,
  project_id INTEGER NOT NULL DEFAULT 1 REFERENCES projects(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS winback_sequences (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  deal_id INTEGER NOT NULL REFERENCES deals(id),
  contact_id INTEGER NOT NULL REFERENCES contacts(id),
  reason TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  started_at TEXT NOT NULL,
  finished_at TEXT,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  contact_id INTEGER REFERENCES contacts(id),
  deal_id INTEGER REFERENCES deals(id),
  due_date TEXT,
  done INTEGER NOT NULL DEFAULT 0,
  done_at TEXT,
  demo INTEGER NOT NULL DEFAULT 0,
  winback_sequence_id INTEGER REFERENCES winback_sequences(id),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by INTEGER
);

CREATE TABLE IF NOT EXISTS interactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER NOT NULL REFERENCES contacts(id),
  deal_id INTEGER REFERENCES deals(id),
  type TEXT NOT NULL DEFAULT 'другое',
  note TEXT DEFAULT '',
  happened_at TEXT NOT NULL,
  demo INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by INTEGER
);

-- tg_*/max_* — два независимых канала уведомлений (ADR-009): падение одного не
-- блокирует другой и не требует повторной отправки туда, куда уже доставлено.
CREATE TABLE IF NOT EXISTS outbox (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,
  payload TEXT NOT NULL,
  tg_attempts INTEGER NOT NULL DEFAULT 0,
  tg_last_error TEXT,
  tg_sent_at TEXT,
  max_sent_at TEXT,
  max_attempts INTEGER NOT NULL DEFAULT 0,
  max_last_error TEXT,
  created_at TEXT NOT NULL
);

-- Права субъекта ПДн (152-ФЗ ст. 14, 20, 21 — ADR-011). contact_id БЕЗ FK — см.
-- преамбулу файла. verified_at — независимый, однажды выставленный факт
-- подтверждения личности, не производная от status (ADR-015).
CREATE TABLE IF NOT EXISTS pd_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER,
  kind TEXT NOT NULL DEFAULT 'delete',
  status TEXT NOT NULL DEFAULT 'new',
  requester TEXT DEFAULT '',
  note TEXT DEFAULT '',
  source TEXT NOT NULL DEFAULT 'manual',
  project_id INTEGER NOT NULL DEFAULT 1 REFERENCES projects(id),
  due_date TEXT NOT NULL,
  resolved_at TEXT,
  resolved_by INTEGER,
  verified_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  user_email TEXT DEFAULT '',
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id INTEGER,
  detail TEXT DEFAULT '',
  created_at TEXT NOT NULL
);

-- Идемпотентность публичного приёма (ТЗ сайта Визор §1.1, ADR-015). Пишутся
-- только терминальные исходы (200/204/400), никогда 429 — тот обязан оставаться
-- повторяемым (см. server/app.js, idempotencyFinish/idempotencyAbandon).
--
-- status_code NULLABLE — единственное осознанное отличие от исходной SQLite-схемы
-- (там был NOT NULL). Нужно для claim-first паттерна (план перевода, раздел про
-- идемпотентность и pg): в SQLite проверка-и-запись были атомарны бесплатно
-- (синхронный однопоточный код, ни одного await между ними) — с асинхронным pg
-- это перестало быть верно, и без явного «застолбления» ключа ДО бизнес-логики
-- два параллельных запроса с одним Idempotency-Key могли бы оба пройти проверку
-- «ключа ещё нет». Строка теперь вставляется со status_code = NULL В МОМЕНТ
-- захвата ключа (до бизнес-логики), UPDATE выставляет реальный код по завершении.
-- Захват — простой INSERT с catch на unique_violation (23505), СПЕЦИАЛЬНО не
-- `ON CONFLICT DO NOTHING RETURNING id`: pg-mem на конфликте возвращает в RETURNING
-- существующую строку вместо пустого набора и тем ломает саму проверку (см.
-- tryClaimIdempotencyKey в server/db-adapter.js).
CREATE TABLE IF NOT EXISTS idempotency_keys (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,
  request_id TEXT NOT NULL,
  status_code INTEGER,
  created_at TEXT NOT NULL,
  UNIQUE (scope, request_id)
);

-- Слепок согласия на обработку ПДн (152-ФЗ ст.9 — ADR-015). contact_id/deal_id
-- БЕЗ FK — см. преамбулу файла. requester — независимое от contact_id
-- доказательство личности (раунд 17). text_truncated — раунды 22/25/27.
CREATE TABLE IF NOT EXISTS consents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id INTEGER,
  deal_id INTEGER,
  project_id INTEGER NOT NULL DEFAULT 1 REFERENCES projects(id),
  requester TEXT NOT NULL DEFAULT '',
  version TEXT NOT NULL DEFAULT '',
  text TEXT NOT NULL DEFAULT '',
  text_truncated INTEGER NOT NULL DEFAULT 0,
  accepted_at TEXT,
  created_at TEXT NOT NULL
);

-- ---------- индексы ----------

CREATE INDEX IF NOT EXISTS idx_deals_contact ON deals(contact_id);
CREATE INDEX IF NOT EXISTS idx_deals_stage ON deals(stage);
CREATE INDEX IF NOT EXISTS idx_tasks_contact ON tasks(contact_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_interactions_contact ON interactions(contact_id);
-- Составной, под производную таблицу в блоке «Остывают» на дашборде
-- (SELECT contact_id, MAX(happened_at) ... GROUP BY contact_id): без него агрегат
-- считается по всей таблице взаимодействий на каждое открытие дашборда, и цена
-- растёт вместе с историей переписок, а не с числом живых сделок.
CREATE INDEX IF NOT EXISTS idx_interactions_contact_happened ON interactions(contact_id, happened_at);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox(tg_sent_at) WHERE tg_sent_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_outbox_pending_max ON outbox(max_sent_at) WHERE max_sent_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_contacts_updated ON contacts(updated_at);
CREATE INDEX IF NOT EXISTS idx_deals_updated ON deals(updated_at);
CREATE INDEX IF NOT EXISTS idx_tasks_updated ON tasks(updated_at);
CREATE INDEX IF NOT EXISTS idx_interactions_updated ON interactions(updated_at);
CREATE INDEX IF NOT EXISTS idx_contacts_inbox ON contacts(source, archived, created_at);

CREATE INDEX IF NOT EXISTS idx_contacts_project ON contacts(project_id, archived, created_at);
CREATE INDEX IF NOT EXISTS idx_deals_project ON deals(project_id, stage);

CREATE INDEX IF NOT EXISTS idx_winback_deal ON winback_sequences(deal_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_winback ON tasks(winback_sequence_id);

CREATE INDEX IF NOT EXISTS idx_pd_open ON pd_requests(status, due_date);
CREATE INDEX IF NOT EXISTS idx_pd_contact ON pd_requests(contact_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity, entity_id);

CREATE INDEX IF NOT EXISTS idx_idempotency_created ON idempotency_keys(created_at);
CREATE INDEX IF NOT EXISTS idx_consents_contact ON consents(contact_id);
